version: "3.8"

services:
  test_studio:
    image: test_studio
    container_name: test_studio
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.test
    environment:
      PYTHONPATH: .
      TZ: Asia/Tokyo
    command: bash -c "poetry install --no-root --with test && poetry run python3 -m pytest -s ."
    volumes:
      - .:/app

  test_studio_frontend:
    image: test_studio_frontend
    container_name: test_studio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      TZ: Asia/Tokyo
    command: yarn test:ci

  build_studio_frontend:
    image: build_studio_frontend
    container_name: build_studio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./frontend/build:/app/build:cached
