version: "3.7"
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      # - backend
      - frontend
  # backend:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   command: python main.py
  #   tty: true
  #   volumes:
  #     - ./backend:/app/:cached
  #     - ./.docker/.ipython:/root/.ipython:cached
  #   environment:
  #     PYTHONPATH: .
  #     TZ: Asia/Tokyo
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - "./frontend:/app:cached"
      - "./frontend/node_modules:/app/node_modules:cached"
    environment:
      - NODE_ENV=development
