version: "3.8"

services:
  test_studio:
    image: test_studio
    container_name: test_studio
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.test
    environment:
      PYTHONPATH: .
      TZ: Asia/Tokyo
    volumes:
      - ./studio:/app/studio
      - ./conda/yaml:/app/conda/yaml
      - ./studio/test_data:/tmp/studio

  test_studio_frontend:
    image: test_studio_frontend
    container_name: test_studio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      TZ: Asia/Tokyo
    command: yarn test:ci

  build_studio_frontend:
    image: build_studio_frontend
    container_name: build_studio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.build
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./frontend/build:/app/build:cached
