version: "3"

services:
  db:
    image: mysql:8.4
    ports:
      - "127.0.0.1:13306:3306"
    env_file:
      - studio/config/.env
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3

  studio-dev-be:
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
      # optinist data outputs directories
      - ../optinist-docker-volumes/.snakemake/:/app/.snakemake
      - ../optinist-docker-volumes/logs/:/app/logs
      - ../optinist-docker-volumes/studio_data/:/app/studio_data
    ports:
      - "127.0.0.1:8000:8000"
    command: >
        bash -c "
          alembic upgrade head &&
          poetry run python main.py --reload --host 0.0.0.0 --port 8000
        "
    environment:
      PYTHONPATH: /app/
      TZ: Asia/Tokyo
      OPTINIST_DIR: /app/studio_data
    depends_on:
      db:
        condition: service_healthy

  studio-dev-fe:
    image: node:20.8.0-alpine3.18
    working_dir: /app/frontend
    volumes:
      - ./frontend/:/app/frontend/:cached
    ports:
      - "127.0.0.1:3000:3000"
    command: ash -c 'yarn install && yarn start'
    environment:
      TZ: Asia/Tokyo

volumes:
  db_data:
