last_output:
- test_data/snakemake/2/suite2p_roi.pkl
rules:
  '0':
    hdf5Path: null
    input:
    - data_endoscope.tif
    nwbfile:
      device:
        description: Microscope Information
        manufacturer: Microscope Manufacture
        name: Microscope device
      experiment_description: None
      identifier: optinist
      image_series:
        name: TwoPhotonSeries
        starting_frame: 0
        starting_time: 0
      imaging_plane:
        description: standard
        excitation_lambda: 600.0
        imaging_rate: 30.0
        indicator: GCaMap
        location: V1
        name: ImagingPlane
      ophys:
        plane_segmentation:
          description: ''
          name: PlaneSegmentation
      optical_channel:
        description: optical channel
        emission_lambda: 500.0
        name: OpticalChannel
      session_description: optinist
    output: test_data/snakemake/0/data_endoscope.pkl
    params: {}
    path: null
    return_arg: '0'
    rule_file: rules/smk/image.smk
    type: image
  RBM675AAxiTY7J8aXP_nh:
    hdf5Path: null
    input:
    - test_data/snakemake/0/data_endoscope.pkl
    nwbfile: null
    output: test_data/snakemake/1/suite2p_file_convert.pkl
    params:
      batch_size: 500
      do_registration: 1
      force_sktiff: false
      nchannels: 1
      nplanes: 1
    path: suite2p/suite2p_file_convert
    return_arg:
      '0': image
    rule_file: rules/smk/suite2p/suite2p_file_convert.smk
    type: suite2p_file_convert
  vUyi1TzpuUVDtSwTb-EFp:
    hdf5Path: null
    input:
    - test_data/snakemake/1/suite2p_file_convert.pkl
    nwbfile: null
    output: test_data/snakemake/2/suite2p_roi.pkl
    params:
      allow_overlap: false
      fs: 10
      high_pass: 100
      inner_neuropil_radius: 2
      max_iterations: 20
      max_overlap: 0.75
      min_neuropil_pixels: 350
      nbinned: 5000
      neucoeff: 0.7
      preclassify: 0
      soma_crop: true
      sparse_mode: true
      spatial_hp_detect: 25
      spatial_scale: 0
      tau: 1
      threshold_scaling: 1
    path: suite2p/suite2p_roi
    return_arg:
      ops: ops
    rule_file: rules/smk/suite2p/suite2p_roi.smk
    type: suite2p_roi
