name: Python Linters
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'notebooks/**'
      - 'frontend/**'
      - 'sample_data/**'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: python -m pip install flake8
      - uses: liskin/gh-problem-matcher-wrap@a89a18291dcde8d4e6158adf736b5432987bbf95
        with:
          linters: flake8
          run: flake8
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: python -m pip install isort
      - uses: liskin/gh-problem-matcher-wrap@a89a18291dcde8d4e6158adf736b5432987bbf95
        with:
          linters: isort
          run: isort --check --diff studio
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          version: "~= 23.11"
