
# whether standardize the data or not
standard_mean: True
standard_std: True

transpose: True

TSNE:
  n_components: 2
  perplexity: 30.0
  early_exaggeration: 12.0
  learning_rate: 'warn'
  n_iter: 1000
  n_iter_without_progress: 300
  min_grad_norm: 0.0000001
  metric: 'euclidean'
  init: 'warn'
  random_state: 0
  method: 'barnes_hut'
  angle: 0.5
  n_jobs: 1
  square_distances: 'legacy'